// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDoListManagement.Entity.Data;

#nullable disable

namespace ToDoListManagement.Entity.Migrations
{
    [DbContext(typeof(ToDoListDbContext))]
    [Migration("20250716042939_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToDoListManagement.Entity.Models.ErrorLog", b =>
                {
                    b.Property<int>("ErrorLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ErrorLogId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.HasKey("ErrorLogId");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Leave", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaveId"));

                    b.Property<string>("AlternatePhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int?>("ApprovalUserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ApprovedOn")
                        .HasColumnType("date");

                    b.Property<string>("CommentByApproval")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsAvailableOnPhone")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("RequestedUserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LeaveId");

                    b.HasIndex("ApprovalUserId");

                    b.HasIndex("RequestedUserId");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<bool>("CanAddEdit")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PermissionName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("PermissionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RoleId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9623),
                            IsDeleted = false,
                            PermissionName = "Projects",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 2,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9659),
                            IsDeleted = false,
                            PermissionName = "Employees",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 3,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9687),
                            IsDeleted = false,
                            PermissionName = "Task Board",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 4,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9714),
                            IsDeleted = false,
                            PermissionName = "Role And Permissions",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 5,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9741),
                            IsDeleted = false,
                            PermissionName = "Self Leave",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 6,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9769),
                            IsDeleted = false,
                            PermissionName = "Team Leave",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 7,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9796),
                            IsDeleted = false,
                            PermissionName = "Manage Team",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 8,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9823),
                            IsDeleted = false,
                            PermissionName = "Projects",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 9,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9851),
                            IsDeleted = false,
                            PermissionName = "Employees",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 10,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9879),
                            IsDeleted = false,
                            PermissionName = "Task Board",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 11,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9906),
                            IsDeleted = false,
                            PermissionName = "Role And Permissions",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 12,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9932),
                            IsDeleted = false,
                            PermissionName = "Self Leave",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 13,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9959),
                            IsDeleted = false,
                            PermissionName = "Team Leave",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 14,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9986),
                            IsDeleted = false,
                            PermissionName = "Manage Team",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 15,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(13),
                            IsDeleted = false,
                            PermissionName = "Projects",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 16,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(42),
                            IsDeleted = false,
                            PermissionName = "Employees",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 17,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(69),
                            IsDeleted = false,
                            PermissionName = "Task Board",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 18,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(100),
                            IsDeleted = false,
                            PermissionName = "Role And Permissions",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 19,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(128),
                            IsDeleted = false,
                            PermissionName = "Self Leave",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 20,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(155),
                            IsDeleted = false,
                            PermissionName = "Team Leave",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 21,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(183),
                            IsDeleted = false,
                            PermissionName = "Manage Team",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 22,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(221),
                            IsDeleted = false,
                            PermissionName = "Projects",
                            RoleId = 4
                        },
                        new
                        {
                            PermissionId = 23,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(250),
                            IsDeleted = false,
                            PermissionName = "Employees",
                            RoleId = 4
                        },
                        new
                        {
                            PermissionId = 24,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(379),
                            IsDeleted = false,
                            PermissionName = "Task Board",
                            RoleId = 4
                        },
                        new
                        {
                            PermissionId = 25,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(406),
                            IsDeleted = false,
                            PermissionName = "Role And Permissions",
                            RoleId = 4
                        },
                        new
                        {
                            PermissionId = 26,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(433),
                            IsDeleted = false,
                            PermissionName = "Self Leave",
                            RoleId = 4
                        },
                        new
                        {
                            PermissionId = 27,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(460),
                            IsDeleted = false,
                            PermissionName = "Team Leave",
                            RoleId = 4
                        },
                        new
                        {
                            PermissionId = 28,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(487),
                            IsDeleted = false,
                            PermissionName = "Manage Team",
                            RoleId = 4
                        },
                        new
                        {
                            PermissionId = 29,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(515),
                            IsDeleted = false,
                            PermissionName = "Projects",
                            RoleId = 5
                        },
                        new
                        {
                            PermissionId = 30,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(542),
                            IsDeleted = false,
                            PermissionName = "Employees",
                            RoleId = 5
                        },
                        new
                        {
                            PermissionId = 31,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(568),
                            IsDeleted = false,
                            PermissionName = "Task Board",
                            RoleId = 5
                        },
                        new
                        {
                            PermissionId = 32,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(595),
                            IsDeleted = false,
                            PermissionName = "Role And Permissions",
                            RoleId = 5
                        },
                        new
                        {
                            PermissionId = 33,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(623),
                            IsDeleted = false,
                            PermissionName = "Self Leave",
                            RoleId = 5
                        },
                        new
                        {
                            PermissionId = 34,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(652),
                            IsDeleted = false,
                            PermissionName = "Team Leave",
                            RoleId = 5
                        },
                        new
                        {
                            PermissionId = 35,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(679),
                            IsDeleted = false,
                            PermissionName = "Manage Team",
                            RoleId = 5
                        },
                        new
                        {
                            PermissionId = 36,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(706),
                            IsDeleted = false,
                            PermissionName = "Projects",
                            RoleId = 6
                        },
                        new
                        {
                            PermissionId = 37,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(732),
                            IsDeleted = false,
                            PermissionName = "Employees",
                            RoleId = 6
                        },
                        new
                        {
                            PermissionId = 38,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(758),
                            IsDeleted = false,
                            PermissionName = "Task Board",
                            RoleId = 6
                        },
                        new
                        {
                            PermissionId = 39,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(785),
                            IsDeleted = false,
                            PermissionName = "Role And Permissions",
                            RoleId = 6
                        },
                        new
                        {
                            PermissionId = 40,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(814),
                            IsDeleted = false,
                            PermissionName = "Self Leave",
                            RoleId = 6
                        },
                        new
                        {
                            PermissionId = 41,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(842),
                            IsDeleted = false,
                            PermissionName = "Team Leave",
                            RoleId = 6
                        },
                        new
                        {
                            PermissionId = 42,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(871),
                            IsDeleted = false,
                            PermissionName = "Manage Team",
                            RoleId = 6
                        },
                        new
                        {
                            PermissionId = 43,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(898),
                            IsDeleted = false,
                            PermissionName = "Projects",
                            RoleId = 7
                        },
                        new
                        {
                            PermissionId = 44,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(926),
                            IsDeleted = false,
                            PermissionName = "Employees",
                            RoleId = 7
                        },
                        new
                        {
                            PermissionId = 45,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(963),
                            IsDeleted = false,
                            PermissionName = "Task Board",
                            RoleId = 7
                        },
                        new
                        {
                            PermissionId = 46,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(991),
                            IsDeleted = false,
                            PermissionName = "Role And Permissions",
                            RoleId = 7
                        },
                        new
                        {
                            PermissionId = 47,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1018),
                            IsDeleted = false,
                            PermissionName = "Self Leave",
                            RoleId = 7
                        },
                        new
                        {
                            PermissionId = 48,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1045),
                            IsDeleted = false,
                            PermissionName = "Team Leave",
                            RoleId = 7
                        },
                        new
                        {
                            PermissionId = 49,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1074),
                            IsDeleted = false,
                            PermissionName = "Manage Team",
                            RoleId = 7
                        },
                        new
                        {
                            PermissionId = 50,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1102),
                            IsDeleted = false,
                            PermissionName = "Projects",
                            RoleId = 8
                        },
                        new
                        {
                            PermissionId = 51,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1128),
                            IsDeleted = false,
                            PermissionName = "Employees",
                            RoleId = 8
                        },
                        new
                        {
                            PermissionId = 52,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1155),
                            IsDeleted = false,
                            PermissionName = "Task Board",
                            RoleId = 8
                        },
                        new
                        {
                            PermissionId = 53,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1182),
                            IsDeleted = false,
                            PermissionName = "Role And Permissions",
                            RoleId = 8
                        },
                        new
                        {
                            PermissionId = 54,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1208),
                            IsDeleted = false,
                            PermissionName = "Self Leave",
                            RoleId = 8
                        },
                        new
                        {
                            PermissionId = 55,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1235),
                            IsDeleted = false,
                            PermissionName = "Team Leave",
                            RoleId = 8
                        },
                        new
                        {
                            PermissionId = 56,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1262),
                            IsDeleted = false,
                            PermissionName = "Manage Team",
                            RoleId = 8
                        },
                        new
                        {
                            PermissionId = 57,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1287),
                            IsDeleted = false,
                            PermissionName = "Projects",
                            RoleId = 9
                        },
                        new
                        {
                            PermissionId = 58,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1315),
                            IsDeleted = false,
                            PermissionName = "Employees",
                            RoleId = 9
                        },
                        new
                        {
                            PermissionId = 59,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1341),
                            IsDeleted = false,
                            PermissionName = "Task Board",
                            RoleId = 9
                        },
                        new
                        {
                            PermissionId = 60,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1367),
                            IsDeleted = false,
                            PermissionName = "Role And Permissions",
                            RoleId = 9
                        },
                        new
                        {
                            PermissionId = 61,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1395),
                            IsDeleted = false,
                            PermissionName = "Self Leave",
                            RoleId = 9
                        },
                        new
                        {
                            PermissionId = 62,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1422),
                            IsDeleted = false,
                            PermissionName = "Team Leave",
                            RoleId = 9
                        },
                        new
                        {
                            PermissionId = 63,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1448),
                            IsDeleted = false,
                            PermissionName = "Manage Team",
                            RoleId = 9
                        },
                        new
                        {
                            PermissionId = 64,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1476),
                            IsDeleted = false,
                            PermissionName = "Projects",
                            RoleId = 10
                        },
                        new
                        {
                            PermissionId = 65,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1503),
                            IsDeleted = false,
                            PermissionName = "Employees",
                            RoleId = 10
                        },
                        new
                        {
                            PermissionId = 66,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1532),
                            IsDeleted = false,
                            PermissionName = "Task Board",
                            RoleId = 10
                        },
                        new
                        {
                            PermissionId = 67,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1569),
                            IsDeleted = false,
                            PermissionName = "Role And Permissions",
                            RoleId = 10
                        },
                        new
                        {
                            PermissionId = 68,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1597),
                            IsDeleted = false,
                            PermissionName = "Self Leave",
                            RoleId = 10
                        },
                        new
                        {
                            PermissionId = 69,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1624),
                            IsDeleted = false,
                            PermissionName = "Team Leave",
                            RoleId = 10
                        },
                        new
                        {
                            PermissionId = 70,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1652),
                            IsDeleted = false,
                            PermissionName = "Manage Team",
                            RoleId = 10
                        },
                        new
                        {
                            PermissionId = 71,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1678),
                            IsDeleted = false,
                            PermissionName = "Projects",
                            RoleId = 11
                        },
                        new
                        {
                            PermissionId = 72,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1705),
                            IsDeleted = false,
                            PermissionName = "Employees",
                            RoleId = 11
                        },
                        new
                        {
                            PermissionId = 73,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1732),
                            IsDeleted = false,
                            PermissionName = "Task Board",
                            RoleId = 11
                        },
                        new
                        {
                            PermissionId = 74,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1760),
                            IsDeleted = false,
                            PermissionName = "Role And Permissions",
                            RoleId = 11
                        },
                        new
                        {
                            PermissionId = 75,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1785),
                            IsDeleted = false,
                            PermissionName = "Self Leave",
                            RoleId = 11
                        },
                        new
                        {
                            PermissionId = 76,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1813),
                            IsDeleted = false,
                            PermissionName = "Team Leave",
                            RoleId = 11
                        },
                        new
                        {
                            PermissionId = 77,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 197, DateTimeKind.Utc).AddTicks(1841),
                            IsDeleted = false,
                            PermissionName = "Manage Team",
                            RoleId = 11
                        });
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<int?>("AssignedToProgramManager")
                        .HasColumnType("integer");

                    b.Property<int?>("AssignedToScrumMaster")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ProjectId");

                    b.HasIndex("AssignedToProgramManager");

                    b.HasIndex("AssignedToScrumMaster");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.ProjectUser", b =>
                {
                    b.Property<int>("ProjectUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectUserId"));

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectUserId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUsers");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9251),
                            IsDeleted = false,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9313),
                            IsDeleted = false,
                            RoleName = "Program Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9341),
                            IsDeleted = false,
                            RoleName = "Member"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9370),
                            IsDeleted = false,
                            RoleName = "Scrum Master"
                        },
                        new
                        {
                            RoleId = 5,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9397),
                            IsDeleted = false,
                            RoleName = "Project Manager"
                        },
                        new
                        {
                            RoleId = 6,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9428),
                            IsDeleted = false,
                            RoleName = "Associative Project Manager"
                        },
                        new
                        {
                            RoleId = 7,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9455),
                            IsDeleted = false,
                            RoleName = "Senior Team Leader"
                        },
                        new
                        {
                            RoleId = 8,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9482),
                            IsDeleted = false,
                            RoleName = "Team Leader"
                        },
                        new
                        {
                            RoleId = 9,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9509),
                            IsDeleted = false,
                            RoleName = "Senior Software Engineer"
                        },
                        new
                        {
                            RoleId = 10,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9552),
                            IsDeleted = false,
                            RoleName = "Software Engineer"
                        },
                        new
                        {
                            RoleId = 11,
                            CreatedAt = new DateTime(2025, 7, 16, 4, 29, 39, 196, DateTimeKind.Utc).AddTicks(9580),
                            IsDeleted = false,
                            RoleName = "Trainee Software Engineer"
                        });
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Sprint", b =>
                {
                    b.Property<int>("SprintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SprintId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("ScrumMasterId")
                        .HasColumnType("integer");

                    b.Property<string>("SprintName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("SprintId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ScrumMasterId");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.TaskAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttachmentId"));

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsImage")
                        .HasColumnType("boolean");

                    b.Property<int?>("TaskId")
                        .HasColumnType("integer");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UploadedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AttachmentId");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("TaskId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("TaskAttachments");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.TeamUserMapping", b =>
                {
                    b.Property<int>("TeamUserMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamUserMappingId"));

                    b.Property<DateOnly?>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("TeamManagerId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("UpdatedAt")
                        .HasColumnType("date");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TeamUserMappingId");

                    b.HasIndex("TeamManagerId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamUserMappings");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.ToDoList", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("SprintId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SprintId");

                    b.ToTable("ToDoLists");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int?>("ReportingPersonId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ReportingPersonId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@outlook.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Admin",
                            PasswordHash = "$2a$11$YCiiJxUwumHUtegC05ahFej29UzVm/s1HRwPriPIuta4b.GWddWuW",
                            PhoneNumber = "9988556644",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Leave", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.User", "ApprovalUser")
                        .WithMany()
                        .HasForeignKey("ApprovalUserId");

                    b.HasOne("ToDoListManagement.Entity.Models.User", "RequestedUser")
                        .WithMany()
                        .HasForeignKey("RequestedUserId");

                    b.Navigation("ApprovalUser");

                    b.Navigation("RequestedUser");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Permission", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.User", "CreatedByNavigation")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("ToDoListManagement.Entity.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToDoListManagement.Entity.Models.User", "UpdatedByNavigation")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Role");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Project", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.User", "AssignedPM")
                        .WithMany()
                        .HasForeignKey("AssignedToProgramManager");

                    b.HasOne("ToDoListManagement.Entity.Models.User", "ScrumMaster")
                        .WithMany()
                        .HasForeignKey("AssignedToScrumMaster");

                    b.HasOne("ToDoListManagement.Entity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("AssignedPM");

                    b.Navigation("ScrumMaster");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.ProjectUser", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.Project", "Project")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectId");

                    b.HasOne("ToDoListManagement.Entity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Sprint", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToDoListManagement.Entity.Models.User", "ScrumMaster")
                        .WithMany()
                        .HasForeignKey("ScrumMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ScrumMaster");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.TaskAttachment", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ToDoListManagement.Entity.Models.ToDoList", "ToDoList")
                        .WithMany()
                        .HasForeignKey("TaskId");

                    b.HasOne("ToDoListManagement.Entity.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedBy");

                    b.Navigation("DeletedByUser");

                    b.Navigation("ToDoList");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.TeamUserMapping", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.User", "TeamManager")
                        .WithMany()
                        .HasForeignKey("TeamManagerId");

                    b.HasOne("ToDoListManagement.Entity.Models.User", "TeamMember")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("TeamManager");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.ToDoList", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedTo");

                    b.HasOne("ToDoListManagement.Entity.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("ToDoListManagement.Entity.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("ToDoListManagement.Entity.Models.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId");

                    b.Navigation("AssignedUser");

                    b.Navigation("CreatedUser");

                    b.Navigation("Project");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.User", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.User", "ReportingPerson")
                        .WithMany()
                        .HasForeignKey("ReportingPersonId");

                    b.HasOne("ToDoListManagement.Entity.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportingPerson");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Project", b =>
                {
                    b.Navigation("ProjectUsers");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
